version: '3.8'

services:
  db:
    image: postgres:15
    container_name: gorevtakip-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: GorevTakipDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Verilerin kalıcı olması için volume

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gorevtakip-api
    depends_on:
      - db
    ports:
      - "5074:8080" # Dışarıdan localhost:5074, içeride 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Host kısmını localhost yerine container adı olan 'db' ile değiştiriyoruz
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=GorevTakipDb;Username=postgres;Password=${DB_PASSWORD}
      - Jwt__Key=${JWT_SECRET_KEY}
    volumes:
      - ./GorevTakip.API/wwwroot:/app/wwwroot # YENİ: Host'taki klasörü container'a bağladık

volumes:
  postgres_data: